package com.kaii.dentix.domain.intakeSurvey;

import com.kaii.dentix.domain.user.domain.User;
import com.kaii.dentix.domain.type.YnType;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.*;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.data.domain.PageRequest;
import java.util.Date;
import static org.assertj.core.api.Assertions.*;

@DataJpaTest(properties = {
    "spring.datasource.url=jdbc:h2:mem:adminsurvey;MODE=MySQL;NON_KEYWORDS=USER;DB_CLOSE_DELAY=-1",
    "spring.datasource.driver-class-name=org.h2.Driver", "spring.datasource.username=sa", "spring.datasource.password=",
    "spring.jpa.hibernate.ddl-auto=none", "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
// Existing entities use MySQL-specific bare enum column definitions. Only the two
// tables exercised by this query are created with equivalent H2-compatible types.
@org.springframework.test.context.jdbc.Sql(statements = {
    "CREATE TABLE IF NOT EXISTS user (user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created TIMESTAMP, modified TIMESTAMP, deleted TIMESTAMP, user_login_identifier VARCHAR(45), user_password VARCHAR(255), user_name VARCHAR(100), user_phone_number VARCHAR(45), user_birth_date VARCHAR(10), real_organization VARCHAR(20), oral_analysis_service_enabled BOOLEAN, user_gender VARCHAR(20), find_pwd_question_id BIGINT, find_pwd_answer VARCHAR(255), user_refresh_token VARCHAR(255), success_count INTEGER, user_last_login_date TIMESTAMP, is_verify VARCHAR(10), daegu_did VARCHAR(255), daegu_did_key VARCHAR(255), daegu_did_status VARCHAR(20), organization_id BIGINT)",
    "CREATE TABLE IF NOT EXISTS user_intake_survey (user_id BIGINT PRIMARY KEY, template_version VARCHAR(40), answers_json TEXT, scores_json TEXT, current_tab INTEGER, updated_at TIMESTAMP WITH TIME ZONE, completed_at TIMESTAMP WITH TIME ZONE, revision BIGINT)"
})
class AdminIntakeSurveyQueryTest {
    @org.springframework.boot.test.mock.mockito.MockBean com.querydsl.jpa.impl.JPAQueryFactory queryFactory;
    @Autowired TestEntityManager em;
    @Autowired AdminIntakeSurveyRepository repository;
    User create(String name, String org) {
        var u = User.builder().userName(name).userLoginIdentifier(name).userPassword("test")
            .userPhoneNumber("000").findPwdQuestionId(1L).findPwdAnswer("test").isVerify(YnType.Y).realOrganization(org).build();
        em.persist(u); return u;
    }
    @Test void includesMissingSurveysFiltersInstitutionsAndExcludesDeletedUsers() {
        var fresh = create("fresh", "대구1");
        var draft = create("draft", "대구1");
        var completed = create("done", "대구2");
        create("unassigned", null);
        var deleted = create("deleted", "대구3"); deleted.setDeleted(new Date());
        var s = new UserIntakeSurvey(draft.getUserId()); s.save("v1", "{}", "{}", 1, false); em.persist(s);
        s = new UserIntakeSurvey(completed.getUserId()); s.save("v1", "{}", "{}", 7, true); em.persist(s);
        em.flush(); em.clear();
        var paging = PageRequest.of(0, 20);
        assertThat(repository.search(null, "", "ALL", paging).getTotalElements()).isEqualTo(4);
        assertThat(repository.search("대구1", "", "NOT_STARTED", paging).getContent())
            .extracting(AdminIntakeSurveyRepository.Summary::getUserId).containsExactly(fresh.getUserId());
        assertThat(repository.search(null, "", "DRAFT", paging).getContent()).hasSize(1);
        assertThat(repository.search(null, "done", "COMPLETED", paging).getContent()).hasSize(1);
        assertThat(repository.search("", "", "ALL", paging).getContent()).hasSize(1);
        assertThat(repository.search(null, "", "ALL", PageRequest.of(0, 1)).getTotalElements()).isEqualTo(4);
        assertThat(repository.organizations()).containsExactly("", "대구1", "대구2");
    }
}
