package com.kaii.dentix.domain.oralExercise;
import com.kaii.dentix.domain.oralExercise.dao.OralExerciseInteractionLogRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.*;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.test.context.jdbc.Sql;
import static org.assertj.core.api.Assertions.*;
@DataJpaTest(properties = {
 "spring.datasource.url=jdbc:h2:mem:exercisehistory;MODE=MySQL;NON_KEYWORDS=USER;DB_CLOSE_DELAY=-1",
 "spring.datasource.driver-class-name=org.h2.Driver", "spring.datasource.username=sa", "spring.datasource.password=",
 "spring.jpa.hibernate.ddl-auto=none", "spring.jpa.database-platform=org.hibernate.dialect.H2Dialect"
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Sql(statements = {
 "CREATE TABLE IF NOT EXISTS user (user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, created TIMESTAMP, modified TIMESTAMP, deleted TIMESTAMP, user_login_identifier VARCHAR(45), user_password VARCHAR(255), user_name VARCHAR(100), user_phone_number VARCHAR(45), user_birth_date VARCHAR(10), real_organization VARCHAR(20), oral_analysis_service_enabled BOOLEAN, user_gender VARCHAR(20), find_pwd_question_id BIGINT, find_pwd_answer VARCHAR(255), user_refresh_token VARCHAR(255), success_count INTEGER, user_last_login_date TIMESTAMP, is_verify VARCHAR(10), daegu_did VARCHAR(255), daegu_did_key VARCHAR(255), daegu_did_status VARCHAR(20), organization_id BIGINT)",
 "CREATE TABLE IF NOT EXISTS user_oral_exercise_progress (user_oral_exercise_progress_id BIGINT PRIMARY KEY, user_id BIGINT)",
 "CREATE TABLE IF NOT EXISTS oral_exercise_interaction_log (oral_exercise_interaction_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT, oral_exercise_content_id BIGINT, event_type VARCHAR(20), session_id VARCHAR(100), completed BOOLEAN, created TIMESTAMP, modified TIMESTAMP, watched_seconds INT, current_position_seconds INT, duration_seconds INT, completion_rate INT)",
 "DELETE FROM user",
 "DELETE FROM oral_exercise_interaction_log",
 "INSERT INTO user(user_id,user_name,user_login_identifier,real_organization) VALUES (1,'First','first','대구1'), (2,'Second','second','대구2'), (3,'No viewing','none','대구1')",
 "INSERT INTO oral_exercise_interaction_log(user_id,oral_exercise_content_id,event_type,session_id,completed) VALUES (1,10,'COMPLETE','s1',true),(1,10,'COMPLETE','s1',true),(1,10,'COMPLETE','s2',true),(1,10,'PROGRESS','s3',true),(1,10,'TOKEN_WRONG','s1',false),(1,10,'TOKEN_WRONG','s1',false),(1,10,'TOKEN_TIMEOUT','s2',false),(1,10,'TOKEN_FAILED','s3',false),(1,11,'COMPLETE','s1',true),(2,10,'COMPLETE','s1',true)"
})
class OralExerciseHistoryQueryTest {
 @org.springframework.boot.test.mock.mockito.MockBean com.querydsl.jpa.impl.JPAQueryFactory queryFactory;
 @Autowired OralExerciseInteractionLogRepository repository;
 @Autowired com.kaii.dentix.domain.user.dao.UserRepository users;
 @Test void aggregatesDistinctCompletedSessionsAndSeparatesUsersAndVideos() {
   var rows = repository.summarize(1L);
   assertThat(rows).hasSize(2);
   var first = rows.stream().filter(r -> r.getContentId() == 10L).findFirst().orElseThrow();
   assertThat(first.getCompletedViews()).isEqualTo(2);
   assertThat(first.getFailures()).isEqualTo(3);
   assertThat(first.getWrongCount()).isEqualTo(1);
   assertThat(first.getTimeoutCount()).isEqualTo(1);
   assertThat(first.getErrorCount()).isEqualTo(1);
   assertThat(repository.summarize(2L).get(0).getCompletedViews()).isEqualTo(1);
 }
 @Test void memberSearchIsPagedAndOnlyIncludesUsersWithViewingHistory() {
   var page = org.springframework.data.domain.PageRequest.of(0, 1);
   assertThat(users.findExerciseHistoryMembers("",page).getTotalElements()).isEqualTo(2);
   assertThat(users.findExerciseHistoryMembers("대구1",page).getContent()).extracting(u -> u.getUserId()).containsExactly(1L);
   assertThat(users.findExerciseHistoryMembers("SECOND",page).getContent()).extracting(u -> u.getUserId()).containsExactly(2L);
 }
}
