name: Deploy Spring Boot (api_server) to EC2 Auto Scaling (S3)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      #Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      #Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      #Give permission to gradlew inside api_server
      - name: Give gradlew permission
        run: chmod +x gradlew
        working-directory: api_server

      #Build Spring Boot project inside api_server
      - name: Build JAR inside api_server
        run: ./gradlew clean build -x test -x asciidoctor
        working-directory: api_server

      #Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2  # change if needed

      #Create .env file for environment variables
      - name: Create env file
        run: |
          echo "SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}" > env
          echo "SPRING_PROFILES_ACTIVE=prod" >> env
          echo "🔥 Created env file:"
          cat env

       #Upload JAR & env to S3
      - name: Upload jar & env to S3
        run: |
          JAR_PATH=$(ls api_server/build/libs/*-SNAPSHOT.jar | head -n 1)
          echo "Using JAR: $JAR_PATH"
      
          echo "Uploading bootJar and .env to S3..."
          
          aws s3 cp "$JAR_PATH" "s3://${{ secrets.S3_BUCKET_NAME }}/latest/app.jar" --acl private
          
          aws s3 cp "env" "s3://${{ secrets.S3_BUCKET_NAME }}/latest/.env" --acl private
          
          echo "Upload complete: bootJar + env uploaded to S3"
